[JENKINS-63835] Added BranchName/CommitHash as optional parameters
jenkinsci/appcenter-plugin pull request #53
Opened 2020-10-02 08:18 UTC by RiederAlex

2020-10-05 20:25 UTC, mezpahlan commented
Hi @RiederAlex Apologies for the delay. I'm mega busy at work this week. I'll try and find some time to look over this shortly. Sorry again.

2020-10-10 16:17 UTC, mezpahlan requested changes
I think we should tidy up some small minor points but otherwise really nice PR. Thank you very much for this. And apologies for the delay in getting back to you.

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +
Just a small comment, but I think we should remove this blank space. At the end of this review I'll do this if there aren't other comments that I need your help with.

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +    private static BuildInfo CreateBuildInfo(@Nonnull UploadRequest request) {
Does this need to be static? I'm guessing not.

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +    private static BuildInfo CreateBuildInfo(@Nonnull UploadRequest request) {
I think we should change CreateBuildInfo to createBuildInfo as (in so far as I can tell) it is simply a private method of this class.... not a class itself.

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +    private static BuildInfo CreateBuildInfo(@Nonnull UploadRequest request) {
We should also add the appropriate nullability information here. i.e. `@Nullable`

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +        return new BuildInfo(request.branchName,request.commitHash,null);
Just a quick question do you know what will happen if the user supplies _both_ the branch name and the commit hash? Is that possible? Allowed? Should we protect against this earlier in the transaction?

2020-10-10 16:17 UTC, mezpahlan commented on src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
> +        return new BuildInfo(request.branchName,request.commitHash,null);
Ahh ignore me this seems only be purely informational like the release notes. So I guess this won't fail but will be confusing for the user. But then that's their fault. Hahaha!

2020-10-10 16:41 UTC, mezpahlan commented
Hi @RiederAlex I've resolved the comments in the PR in a local branch of mine but am unable to push them to your repo. In the PR do you have the option to allow maintainers (i.e. me) to submit upates to your branch? And if so can you enable that option please.

2020-10-11 11:54 UTC, RiederAlex commented
> Hi @RiederAlex I've resolved the comments in the PR in a local branch of mine but am unable to push them to your repo. In the PR do you have the option to allow maintainers (i.e. me) to submit upates to your branch? And if so can you enable that option please.

Sadly I just learned that this is not possible directly, as I have forked it as a company account and not as a user account - so I gave you write access directly to the fork - I'm sorry for the inconvenience and thanks for the review!

2020-10-11 14:39 UTC, mezpahlan commented
@RiederAlex Thanks, not a problem. I've pushed my changes and merged in the latest main branch. It's just building now.

2020-10-11 14:58 UTC, merged